export enum ProductActionType {
    LOADING = "LOADING",
    LOAD_SUCCESS = "LOAD_SUCCESS",
    LOAD_FAILURE = "LOAD_FAILURE",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    CREATE_PRODUCT = "CREATE_PRODUCT",
    ADD_PRODUCT_TO_SHOPPING = "ADD_PRODUCT_TO_SHOPPING"
  }